### ISSUE TITLE
Where can find the paper?

### ISSUE THREAD

**Issue by Wenqiang-Miao** [LianaWang/TextRay#1]
Hello, I failed to find the paper, could any body send me a link?

**Comment by sonnguyenasu** [comment]
https://arxiv.org/pdf/2008.04851.pdf
Here it is

**Comment by LianaWang** [comment]
This is the arxiv link: https://arxiv.org/abs/2008.04851

**Comment by Wenqiang-Miao** [comment]
> https://arxiv.org/pdf/2008.04851.pdf
> Here it is

Thanks a lot~
