### ISSUE TITLE
Error when compiling custom operation

### ISSUE THREAD

**Issue by sonnguyenasu** [LianaWang/TextRay#2]
When I set up, there is an error saying:
```
src/iou_cuda.cpp:4:23: error: ‘AT_CHECK’ was not declared in this scope
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
```

I am using cuda 11.0, ubuntu 18.04. Are there any way to work around this? Thank you

**Comment by LianaWang** [comment]
It's the version of pytorch. I use 1.3.1 and in the new versions its TORCH_CHECK instead of AT_CHECK.

**Comment by sonnguyenasu** [comment]
Thank you
