### ISSUE TITLE
pip freeze > requirements.txt

### ISSUE THREAD

**Issue by seekingdeep** [LianaWang/TextRay#3]
I can't build mmdet correctly
add the requirements:

pip freeze > requirements.txt

**Comment by LianaWang** [comment]
Freeze list:
absl-py==0.8.1                                                                                                                                        
addict==2.2.1                                                                                                                                         
albumentations==0.4.3                                                                                                                                 
astor==0.8.0                                                                                                                                          
attrs==19.3.0                                                                                                                                         
backcall==0.1.0                                                                                                                                       
-e git+https://github.com/open-mmlab/mmdetection.git@b57109ed368b42a600fbc9228aedad441a847eb9#egg=bbox_overlap_cpu&subdirectory=mmdet/ops/nms/src     
bleach==3.1.0                                                                                                                                         
certifi==2019.11.28                                                                                                                                   
cffi==1.12.3                                                                                                                                          
chardet==3.0.4                                                                                                                                        
cycler==0.10.0                                                                                                                                        
Cython==0.29.14                                                                                                                                       
decorator==4.4.1                                                                                                                                      
defusedxml==0.6.0                                                                                                                                     
entrypoints==0.3                                                                                                                                      
future==0.17.1                                                                                                                                        
gast==0.2.2                                                                                                                                           
google-pasta==0.1.8                                                                                                                                   
grpcio==1.23.0                                                                                                                                        
h5py==2.9.0                                                                                                                                           
idna==2.8                                                                                                                                             
imagecorruptions==1.0.0
imageio==2.5.0
imgaug==0.2.6
importlib-metadata==1.3.0
ipykernel==5.1.3
ipython==7.11.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.15.2
Jinja2==2.10.3
joblib==0.14.1
json5==0.8.5
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-core==4.6.1
jupyter-highlight-selected-word==0.2.0
jupyter-tensorboard==0.2.0
jupyterlab==1.2.4
jupyterlab-server==1.0.6
jupyterthemes==0.20.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
lesscpy==0.13.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.1
mistune==0.8.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
mmcv==0.2.16
-e git+https://github.com/open-mmlab/mmdetection.git@93bed07bb65b24ae040d797a7696ecb994acf9f5#egg=mmdet&subdirectory=../../mmdetection
more-itertools==8.0.2
mpmath==1.1.0
nbconvert==5.6.1
nbformat==4.4.0
networkx==2.3
notebook==6.0.1
numpy==1.18.1
olefile==0.46
opencv-python==4.1.1.26
opt-einsum==3.1.0
pandas==1.0.3
pandocfilters==1.4.2
parso==0.5.2
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.1.0
ply==3.11
prometheus-client==0.7.1                                                                                                                              
prompt-toolkit==3.0.2                                                                                                                                 
protobuf==3.10.1                                                                                                                                      
ptyprocess==0.6.0                                                                                                                                     
pycocotools==2.0.0
pycparser==2.19
pygeos==0.5
Pygments==2.5.2
pyparsing==2.4.2
pyrsistent==0.15.6
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.0.3
PyYAML==5.1.2
pyzmq==18.1.1
qtconsole==4.5.5
requests==2.22.0
scikit-image==0.15.0
scikit-learn==0.22
scipy==1.4.1
seaborn==0.10.0
Send2Trash==1.5.0
Shapely==1.7.0
six==1.12.0
sklearn==0.0
sympy==1.5
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
terminado==0.8.3
terminaltables==3.1.0
testpath==0.4.4
toposort==1.5
torch==1.3.1
torchvision==0.4.2
tornado==6.0.3
tqdm==4.43.0
traitlets==4.3.3
urllib3==1.25.5
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.16.0
widgetsnbextension==3.5.1
wrapt==1.11.2
zipp==0.6.0
