### ISSUE TITLE
testing the model

### ISSUE THREAD

**Issue by seekingdeep** [LianaWang/TextRay#4]
@LianaWang  hi there

i would like to test the model using cpu only but testing seems somewhat complicated to me
how can i set the input folder, and cpu only?
why don't you create a single test script?

**Comment by LianaWang** [comment]
training and test data are in the same folder organized as data/readme.md.
we use mmdet test tools for single and multiple gpu testing, you can check its cpu test usage.

**Comment by seekingdeep** [comment]
what is the fps for inferencing
