### ISSUE TITLE
编译环境问题

### ISSUE THREAD

**Issue by dpengwen** [LianaWang/TextRay#5]
您好，非常感谢您开源代码。想请问一下您一个问题：我在CUDA10.1 + pytorch 1.2 以及CUDA9.0 + pytorch 1.1环境中，在执行./compile.sh均报如下错误：
src/pip_kernel.cu(49): error: a pointer to a bound function may only be used to call the function

src/pip_kernel.cu(49): error: type name is not allowed

src/pip_kernel.cu(49): error: expected an expression

src/pip_kernel.cu(50): error: a pointer to a bound function may only be used to call the function

src/pip_kernel.cu(50): error: type name is not allowed

src/pip_kernel.cu(50): error: expected an expression

src/pip_kernel.cu(51): error: a pointer to a bound function may only be used to call the function

src/pip_kernel.cu(51): error: type name is not allowed

src/pip_kernel.cu(51): error: expected an expression

9 errors detected in the compilation of "/tmp/tmpxft_00003314_00000000-6_pip_kernel.cpp1.ii".
想请问一下您编写的.cu文件的具体编译环境是什么？

**Comment by LianaWang** [comment]
我用的CUDA10.1+pytorch1.3.1

**Comment by dpengwen** [comment]
> 我用的CUDA10.1+pytorch1.3.1

当我用更高版本的pytorch(如pytorch 1.6)时，仍然会报如上错误，请问这个.cu文件的编译有什么特殊要求吗？

**Comment by LianaWang** [comment]
你的报错我搜索了一下，看起来是CUDA9.0版本导致的，你确认一下编译时候是不是使用了CUDA9.0，我参考的是这个链接：
https://github.com/facebookresearch/SparseConvNet/issues/164

**Comment by dpengwen** [comment]
> 你的报错我搜索了一下，看起来是CUDA9.0版本导致的，你确认一下编译时候是不是使用了CUDA9.0，我参考的是这个链接：
> [facebookresearch/SparseConvNet#164](https://github.com/facebookresearch/SparseConvNet/issues/164)

好的，非常感谢

**Comment by jstacer1** [comment]
> 我用的CUDA10.1+pytorch1.3.1
您好，我们最近有项工作需要复现您的论文，但是组里只有30系以上的卡，请问对应cuda和pytorch版本应该是多少呢
